# Generated by Django 5.1.4 on 2025-01-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_register_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Archivo adjunto'),
        ),
    ]
