# Generated by Django 5.1.4 on 2025-01-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_register_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='estado_envio',
            field=models.CharField(choices=[('no_enviado', 'No Enviado'), ('autenticado', 'Autenticado'), ('workspace_creado', 'Workspace creado'), ('metadata_ingresada', 'Metadata ingresada'), ('archivo_subido', 'Archivo subido'), ('publicado', 'Publicado')], default='no_enviado', max_length=20, verbose_name='Estado de envío'),
        ),
        migrations.AlterField(
            model_name='register',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('procesando', 'Procesando'), ('enviado', 'Enviado')], default='pendiente', max_length=10, verbose_name='Estado'),
        ),
    ]
