# Generated by Django 5.1.4 on 2025-01-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_register_estado_envio_alter_register_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='estado_envio',
            field=models.CharField(choices=[('no_enviado', 'No Enviado'), ('autenticado', 'Autenticado'), ('workspace_creado', 'Workspace creado'), ('metadata_ingresada', 'Metadata ingresada'), ('archivo_subido', 'Archivo subido'), ('publicado', 'Publicado'), ('error', 'Error')], default='no_enviado', max_length=20, verbose_name='Estado de envío'),
        ),
    ]
