# Generated by Django 5.1.4 on 2025-04-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_register_estado_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='workspaceitem_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WorkSpaceItem ID'),
        ),
    ]
