# Generated by Django 5.1.4 on 2025-04-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_register_workspaceitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='item_uuid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item UUID'),
        ),
    ]
