# Generated by Django 5.1.4 on 2025-04-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_register_estado_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='discoverable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Descubrible?'),
        ),
        migrations.AddField(
            model_name='register',
            name='inArchive',
            field=models.BooleanField(blank=True, null=True, verbose_name='Archivado?'),
        ),
        migrations.AddField(
            model_name='register',
            name='withdrawn',
            field=models.BooleanField(blank=True, null=True, verbose_name='Retirado?'),
        ),
    ]
