# Generated by Django 5.1.4 on 2025-05-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_register_discoverable_register_inarchive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='sistema_origen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sistema de origen'),
        ),
    ]
