# Generated by Django 5.1.4 on 2025-01-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DspaceCollection',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255, unique=True)),
                ('uri', models.URLField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
